name: or-inf_transport
channels:
  - tim_shawver
  - conda-forge
  - defaults
dependencies:
  - python>3.8
  - notebook>5.2
  - jupyter_dashboards
  - jupyter_dashboards_bundlers
  - matplotlib
  - pandas
  - geopandas
  - numpy
  - shapely
  - geopy